version: '3.1'
services:
  administration:
    image: carlafgabriela/proiect_idp:latest
    build: ./DatabaseAdministration
    links:
      - database
    ports:
      - 5001:5001
    volumes:
      - ./DatabaseAdministration:/app

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timetable
    volumes:
      - ./DatabaseInitialization:/docker-entrypoint-initdb.d/:ro

  server:
    image: carlafgabriela/proiect_idp:bla
    build: ./Server
    links:
      - database
    ports:
      - 5000:5000
    volumes:
      - ./Server:/app
